// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLUbr_rirM-l1q_D4Vyp705UIHbJF3yIQ',
    appId: '1:31096277285:web:968dd58c5f9b1b0e6df2cc',
    messagingSenderId: '31096277285',
    projectId: 'noteapp-6def1',
    authDomain: 'noteapp-6def1.firebaseapp.com',
    storageBucket: 'noteapp-6def1.firebasestorage.app',
    measurementId: 'G-RSBEHM7BHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMfNR4aYX_CT7NE7myGpNVkRISYRzTBg',
    appId: '1:31096277285:android:e252dc86b7e703d36df2cc',
    messagingSenderId: '31096277285',
    projectId: 'noteapp-6def1',
    storageBucket: 'noteapp-6def1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6CMgxD4wmOFgTwuelE_bPLPTFLhKjtY0',
    appId: '1:31096277285:ios:ed1222c46189ebc16df2cc',
    messagingSenderId: '31096277285',
    projectId: 'noteapp-6def1',
    storageBucket: 'noteapp-6def1.firebasestorage.app',
    androidClientId: '31096277285-8002etj5cj1k3etckfuduu1c4ccn6jfs.apps.googleusercontent.com',
    iosClientId: '31096277285-mq40ev19emook15pko56smkdovca9r1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6CMgxD4wmOFgTwuelE_bPLPTFLhKjtY0',
    appId: '1:31096277285:ios:ed1222c46189ebc16df2cc',
    messagingSenderId: '31096277285',
    projectId: 'noteapp-6def1',
    storageBucket: 'noteapp-6def1.firebasestorage.app',
    androidClientId: '31096277285-8002etj5cj1k3etckfuduu1c4ccn6jfs.apps.googleusercontent.com',
    iosClientId: '31096277285-mq40ev19emook15pko56smkdovca9r1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLUbr_rirM-l1q_D4Vyp705UIHbJF3yIQ',
    appId: '1:31096277285:web:4190cc79a3e5c14f6df2cc',
    messagingSenderId: '31096277285',
    projectId: 'noteapp-6def1',
    authDomain: 'noteapp-6def1.firebaseapp.com',
    storageBucket: 'noteapp-6def1.firebasestorage.app',
    measurementId: 'G-TNNHNJMB72',
  );

}